apps/authentication/urls.py
from django.urls import path

from .views import LoginView, LogoutView

app_name = "authentication"

urlpatterns = [
    path(
        route="login/",
        view=LoginView.as_view(),
        name="login",
    ),
    path(
        route="logout/",
        view=LogoutView.as_view(),
        name="logout",
    ),
]

apps/dashboard/urls.py
from django.urls import path

from .views import IndexView

app_name = "dashboard"

urlpatterns = [
    path(
        route="",
        view=IndexView.as_view(),
        name="index",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include("apps.dashboard.urls", namespace="dashboard")),
    path("auth/", include("apps.authentication.urls", namespace="authentication")),
    path("cadastro/", include("apps.cadastro.urls", namespace="cadastro")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path(
            "500/",
            default_views.server_error,
            kwargs={"exception": Exception("Server Error")},
        ),
    ]

apps/templates/includes/footer.html
{% load static %}

<footer class="bg-white rounded shadow p-5 mb-3 mt-4">
    <div class="row">
        <div class="col-12 col-md-4 col-xl-6 mb-4 mb-md-0">
            <p class="mb-0 text-center text-lg-start">
                &copy;RHManager - Grupo 4
            </p>
        </div>
        <div class="col-12 col-md-8 col-xl-6 text-center text-lg-start">
            <ul class="list-inline list-group-flush list-group-borderless text-md-end mb-0">
                <li class="list-inline-item px-0 px-sm-2">
                    <a target="_blank" href="https://ararangua.ufsc.br/">
                        UFSC - Araranguá
                    </a>
                </li>
            </ul>
        </div>
    </div>
</footer>

apps/templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
    <div class="container-fluid px-0">
        <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
            <ul class="navbar-nav align-items-center ms-auto">
                <li class="nav-item dropdown ms-lg-3">
                    <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <div class="media d-flex align-items-center">
                            <img class="avatar rounded-circle" src="{{ request.user.get_profile_picture }}">
                            <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                                <span class="mb-0 font-small fw-bold text-gray-900">
                                    {{ request.user.get_full_name }}
                                </span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
                        {% if user.is_superuser or user.is_staff %}
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'admin:index' %}">
                            <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20"
                                xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                    d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
                                    clip-rule="evenodd">
                                </path>
                            </svg>
                            Painel admin.
                        </a>
                        {% endif %}

                        <div role="separator" class="dropdown-divider my-1"></div>

                        <a class="dropdown-item d-flex align-items-center" href="{% url 'authentication:logout' %}">
                            <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor"
                                viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1">
                                </path>
                            </svg>
                            Sair
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

apps/templates/includes/scripts.html
{% load static %}

<script src="{% static 'vendor/@popperjs/core/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>
<script src="{% static 'vendor/nouislider/distribute/nouislider.min.js' %}"></script>
<script src="{% static 'vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
<script src="{% static 'vendor/countup.js/dist/countUp.umd.js' %}"></script>
<script src="{% static 'vendor/apexcharts/dist/apexcharts.min.js' %}"></script>
<script src="{% static 'vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>
<script src="{% static 'vendor/simple-datatables/dist/umd/simple-datatables.js' %}"></script>
<script src="{% static 'vendor/sweetalert2/dist/sweetalert2.min.js' %}"></script>
<script src="{% static 'vendor/fullcalendar/main.min.js' %}"></script>
<script src="{% static 'vendor/dropzone/dist/min/dropzone.min.js' %}"></script>
<script src="{% static 'vendor/choices.js/public/assets/scripts/choices.min.js' %}"></script>
<script src="{% static 'vendor/notyf/notyf.min.js' %}"></script>
<script src="{% static 'vendor/leaflet/dist/leaflet.js' %}"></script>
<script src="{% static 'vendor/svg-pan-zoom/dist/svg-pan-zoom.min.js' %}"></script>
<script src="{% static 'vendor/svgmap/dist/svgMap.min.js' %}"></script>
<script src="{% static 'vendor/simplebar/dist/simplebar.min.js' %}"></script>
<script src="{% static 'vendor/sortablejs/Sortable.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script async defer src="https://buttons.github.io/buttons.js"></script>
<script src="{% static 'js/volt.js' %}"></script>
<script src="{% static 'app_assets/js/notify.js' %}"></script>
<script src="{% static 'app_assets/js/app_js.js' %}"></script>
<script src="{% static 'app_assets/jquery/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'app_assets/jquery/cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'app_assets/jquery/js/jquery-confirm.min.js' %}"></script>

<script>
{% if messages %}
{% for message in messages %}
notification['{{ message.tags }}']("<p>" + '{{ message|capfirst }}' + "</p>"); 
{% endfor %} 
{% endif %}
</script>

apps/templates/includes/sidebar.html
{% load static %}

<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
    <a class="navbar-brand me-lg-5" href="{% url 'dashboard:index' %}">
        <img class="navbar-brand" src="{% static 'images/logo-text-light.svg' %}">
    </a>
    <div class="d-flex align-items-center">
        <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
    <div class="sidebar-inner px-4 pt-3">
        <div class="user-card d-flex d-md-none justify-content-between justify-content-md-center pb-4">
            <div class="d-flex align-items-center mt-2">
                <div class="avatar-lg me-4">
                    <img src="{{ request.user.get_profile_picture }}" class="card-img-top rounded-circle border-white">
                </div>
                <div class="d-block">
                    <h2 class="h5 mb-3"> Olá, {{ request.user.get_short_name }}! </h2>
                    <a href="{% url 'authentication:logout' %}"
                        class="btn btn-secondary btn-sm d-inline-flex align-items-center">
                        <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1">
                            </path>
                        </svg>
                        Sair
                    </a>
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse" data-bs-target="#sidebarMenu"
                    aria-controls="sidebarMenu" aria-expanded="true" aria-label="Toggle navigation">
                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd">
                        </path>
                    </svg>
                </a>
            </div>
        </div>

        <ul class="nav flex-column pt-3 pt-md-0">
            <li class="nav-item mb-4 mt-2">
                <a href="{% url 'dashboard:index' %}" class="nav-link d-flex align-items-center">
                    <span class="sidebar-icon">
                        <img src="{% static 'images/logo.svg' %}" height="45" width="45">
                    </span>
                    <span class="px-2 mt-2 sidebar-text h5"> RHManager </span>
                </a>
            </li>

            <li class="nav-item {% if 'dashboard:index' in segment %} active {% endif %}">
                <a href="{% url 'dashboard:index' %}" class="nav-link">
                    <span class="sidebar-icon">
                        <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
                            <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
                        </svg>
                    </span>
                    <span class="sidebar-text"> Dashboard </span>
                </a>
            </li>

            <li class="nav-item mt-4 mb-0"><span class="px-2  sidebar-text"> Cadastro </span></li>
            <li role="separator" class="dropdown-divider mb-2 border-gray-700"> </li>

            <li class="nav-item">
                <span class="nav-link d-flex justify-content-between align-items-center" data-bs-toggle="collapse"
                    data-bs-target="#submenu-policiais">
                    <span>
                        <span class="sidebar-icon">
                            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z">
                                </path>
                            </svg>
                        </span>
                        <span class="sidebar-text"> Policiais </span>
                    </span>
                    <span class="link-arrow">
                        <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                clip-rule="evenodd">
                            </path>
                        </svg>
                    </span>
                </span>
                <div class="multi-level collapse {% if 'cadastro:policiais:' in segment %} show {% endif %}" role="list"
                    id="submenu-policiais" aria-expanded="false">
                    <ul class="flex-column nav">
                        <li class="nav-item {% if 'cadastro:policiais:list' in segment %} active {% endif %}">
                            <a href="{% url 'cadastro:policiais:list' %}" class="nav-link">
                                <span class="sidebar-text"> Mostrar </span>
                            </a>
                        </li>
                        <li class="nav-item {% if 'cadastro:policiais:create' in segment %} active {% endif %}">
                            <a href="{% url 'cadastro:policiais:create' %}" class="nav-link">
                                <span class="sidebar-text"> Adicionar </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="nav-item">
                <span class="nav-link d-flex justify-content-between align-items-center" data-bs-toggle="collapse"
                    data-bs-target="#submenu-complementos">
                    <span>
                        <span class="sidebar-icon">
                            <svg class="icon icon-xs me-2" height="0.75em" fill="currentColor" viewBox="0 0 512 512"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M40 48C26.7 48 16 58.7 16 72v48c0 13.3 10.7 24 24 24H88c13.3 0 24-10.7 24-24V72c0-13.3-10.7-24-24-24H40zM192 64c-17.7 0-32 14.3-32 32s14.3 32 32 32H480c17.7 0 32-14.3 32-32s-14.3-32-32-32H192zm0 160c-17.7 0-32 14.3-32 32s14.3 32 32 32H480c17.7 0 32-14.3 32-32s-14.3-32-32-32H192zm0 160c-17.7 0-32 14.3-32 32s14.3 32 32 32H480c17.7 0 32-14.3 32-32s-14.3-32-32-32H192zM16 232v48c0 13.3 10.7 24 24 24H88c13.3 0 24-10.7 24-24V232c0-13.3-10.7-24-24-24H40c-13.3 0-24 10.7-24 24zM40 368c-13.3 0-24 10.7-24 24v48c0 13.3 10.7 24 24 24H88c13.3 0 24-10.7 24-24V392c0-13.3-10.7-24-24-24H40z">
                                </path>
                            </svg>
                        </span>
                        <span class="sidebar-text"> Complementos </span>
                    </span>
                    <span class="link-arrow">
                        <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                clip-rule="evenodd">
                            </path>
                        </svg>
                    </span>
                </span>
                <div class="multi-level collapse {% if 'cadastro:complementos:' in segment %} show {% endif %}"
                    role="list" id="submenu-complementos" aria-expanded="false">
                    <ul class="flex-column nav">
                        <li
                            class="nav-item {% if 'cadastro:complementos:formacao_academica' in segment %} active {% endif %}">
                            <a href="{% url 'cadastro:complementos:formacao_academica_list' %}" class="nav-link">
                                <span class="sidebar-text"> Formações Acd. </span>
                            </a>
                        </li>
                    </ul>
                    <ul class="flex-column nav">
                        <li class="nav-item {% if 'cadastro:complementos:curso_geral' in segment %} active {% endif %}">
                            <a href="{% url 'cadastro:complementos:curso_geral_list' %}" class="nav-link">
                                <span class="sidebar-text"> Cursos </span>
                            </a>
                        </li>
                        <li class="nav-item {% if 'cadastro:complementos:curso_pm' in segment %} active {% endif %}">
                            <a href="{% url 'cadastro:complementos:curso_pm_list' %}" class="nav-link">
                                <span class="sidebar-text"> Cursos PM </span>
                            </a>
                        </li>
                        <li class="nav-item {% if 'cadastro:complementos:curso_civil' in segment %} active {% endif %}">
                            <a href="{% url 'cadastro:complementos:curso_civil_list' %}" class="nav-link">
                                <span class="sidebar-text"> Cursos Civis </span>
                            </a>
                        </li>
                        <li
                            class="nav-item {% if 'cadastro:complementos:lingua_estrangeira' in segment %} active {% endif %}">
                            <a href="{% url 'cadastro:complementos:lingua_estrangeira_list' %}" class="nav-link">
                                <span class="sidebar-text"> Linguas Estrang. </span>
                            </a>
                        </li>
                        <li
                            class="nav-item {% if 'cadastro:complementos:tipo_afastamento' in segment %} active {% endif %}">
                            <a href="{% url 'cadastro:complementos:tipo_afastamento_list' %}" class="nav-link">
                                <span class="sidebar-text"> Afastamentos </span>
                            </a>
                        </li>
                        <li
                            class="nav-item {% if 'cadastro:complementos:tipo_restricao' in segment %} active {% endif %}">
                            <a href="{% url 'cadastro:complementos:tipo_restricao_list' %}" class="nav-link">
                                <span class="sidebar-text"> Restrições </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="nav-item mt-4 mb-0"><span class="px-2  sidebar-text"> Relatótrios </span></li>
            <li role="separator" class="dropdown-divider mb-2 border-gray-700"> </li>

            <li class="nav-item {% if 'cadastro:policiais:aposentadoria' in segment %} active {% endif %}">
                <a href="" class="nav-link">
                    <span class="sidebar-icon">
                        <svg class="icon icon-xs me-2" fill="currentColor" height="0.75em" viewBox="0 0 512 512"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M64 64c0-17.7-14.3-32-32-32S0 46.3 0 64V400c0 44.2 35.8 80 80 80H480c17.7 0 32-14.3 32-32s-14.3-32-32-32H80c-8.8 0-16-7.2-16-16V64zm406.6 86.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L320 210.7l-57.4-57.4c-12.5-12.5-32.8-12.5-45.3 0l-112 112c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L240 221.3l57.4 57.4c12.5 12.5 32.8 12.5 45.3 0l128-128z">
                            </path>
                        </svg>
                    </span>
                    <span class="sidebar-text"> Aposentadoria </span>
                </a>
            </li>
        </ul>
    </div>
</nav>