apps/authentication/urls.py
from django.urls import path

from .views import LoginView, LogoutView

app_name = "authentication"

urlpatterns = [
    path(
        route="login/",
        view=LoginView.as_view(),
        name="login",
    ),
    path(
        route="logout/",
        view=LogoutView.as_view(),
        name="logout",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include("apps.dashboard.urls", namespace="dashboard")),
    path("auth/", include("apps.authentication.urls", namespace="authentication")),
    path("cadastro/", include("apps.cadastro.urls", namespace="cadastro")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path(
            "500/",
            default_views.server_error,
            kwargs={"exception": Exception("Server Error")},
        ),
    ]

apps/authentication/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.exceptions import ValidationError
from django.db import models
from django.templatetags.static import static

from .managers import UserManager


class User(AbstractUser):
    username = models.CharField(
        max_length=30,
        unique=True,
        validators=[UnicodeUsernameValidator()],
        verbose_name="Usuário",
        help_text="Obrigatório. 30 caracteres ou menos. Letras, dígitos e @/./+/-/_ apenas.",
    )
    first_name = models.CharField(
        max_length=30,
        blank=True,
        verbose_name="Nome",
    )
    last_name = models.CharField(
        max_length=30,
        blank=True,
        verbose_name="Sobrenome",
    )
    email = None
    is_superuser = models.BooleanField(
        default=False,
        verbose_name="Superusuário",
        help_text="Designa se o usuário tem todas as permissões (incluindo acesso ao painel administrativo).",
    )
    is_staff = models.BooleanField(
        default=False,
        verbose_name="Membro da equipe",
        help_text="Designa se o usuário pode acessar o painel administrativo.",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="Ativo",
        help_text="Designa se o usuário pode fazer login no sistema. Desmarque essa opção em vez de excluir contas.",
    )
    profile_picture = models.ImageField(
        upload_to="images/profile_pictures",
        default=settings.DEFAULT_PROFILE_PICTURE,
        blank=True,
        verbose_name="Foto de perfil",
    )

    objects = UserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"
        ordering = ["username"]

    def __str__(self):
        return self.get_full_name()

    def clean(self):
        super().clean()
        if self.is_superuser and not self.is_staff:
            raise ValidationError("Superusuários devem ser também membros da equipe.")

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def get_full_name(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        return self.get_short_name()

    def get_short_name(self):
        if self.first_name:
            return self.first_name
        return self.username

    def get_profile_picture(self):
        if self.profile_picture and hasattr(self.profile_picture, "url"):
            return self.profile_picture.url
        return static(settings.DEFAULT_PROFILE_PICTURE)

apps/authentication/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Usuário",
                "class": "form-control",
                "id": "id_username",
            }
        ),
        required=True,
    )
    password = forms.CharField(
        max_length=30,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Senha",
                "class": "form-control",
                "id": "id_password",
            },
        ),
        required=True,
    )

apps/authentication/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

from .forms import LoginForm


class LoginView(View):
    form_class = LoginForm
    template_name = "authentication/login.html"
    redirect_authenticated_user = True
    success_url = settings.LOGIN_REDIRECT_URL

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            return redirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            User = get_user_model()
            user = User.objects.filter(username=username).first()
            if user is not None:
                if user.is_active:
                    user = authenticate(request, username=username, password=password)
                    if user is not None:
                        login(request, user)
                        return redirect(self.success_url)
                    else:
                        messages.error(request, "Senha inválida.")
                else:
                    messages.error(request, "Usuário inativo.")
            else:
                messages.error(request, "Usuário não encontrado.")
        else:
            messages.error(request, "Erro ao validar o formulário.")
        return render(request, self.template_name, {"form": form})


class LogoutView(View):
    success_url = settings.LOGOUT_REDIRECT_URL

    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    @method_decorator(csrf_protect)
    def post(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, "Logout realizado com sucesso.")
        return redirect(self.success_url)

    get = post

apps/templates/authentication/login.html
{% extends "layouts/base_fullscreen.html" %}
{% load static %}

{% block title %}
Login
{% endblock %}

{% block content %}
<section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 d-flex align-items-center justify-content-center">
                <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                    <div class="text-center text-md-center mb-4 mt-md-0">
                        <img class="mb-3" src="{% static 'images/logo-text.svg' %}" alt="logo-text" height="60">
                        <br />
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message | safe }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <form action="{% url 'authentication:login' %}" method="post" class="mt-4">
                        {% csrf_token %}
                        <div class="form-group mb-4">
                            <label for="id_username"> Usuário </label>
                            <div class="input-group">
                                <span class="input-group-text" id="basic-addon1">
                                    <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z">
                                        </path>
                                    </svg>
                                </span>
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group mb-4">
                            <label for="id_password"> Senha </label>
                            <div class="input-group">
                                <span class="input-group-text" id="basic-addon2">
                                    <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd"
                                            d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                                            clip-rule="evenodd"></path>
                                    </svg>
                                </span>
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="d-grid">
                            <button type="submit" name="login" class="btn btn-gray-800">
                                Login
                            </button>
                        </div>
                    </form>
                    <br />
                    <div class="d-flex justify-content-center align-items-center mt-4">
                        <span class="fw-normal">
                            &copy;RHManager - Grupo 4
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}